import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { FileText, Trash2, FileJson, Download } from "lucide-react";
import { Card, Badge, EmptyState, Skeleton } from "../components/ui/primitives";
import { ConfirmDialog } from "../components/ui/Dialog";
import { api, mediaUrl } from "../lib/api";
import type { Report } from "../lib/types";
import { timeAgo, fmt, summaryText } from "../lib/format";
import { useInvalidate } from "../hooks/useData";
import { useToast } from "../hooks/useToast";

const KIND_TONE: Record<string, "green" | "amber" | "red" | "blue" | "gray"> = {
  panel: "blue", panel_analysis: "blue", inspection: "amber", attendance: "green", training: "gray",
};

export default function Reports() {
  const invalidate = useInvalidate();
  const { push } = useToast();
  const [kind, setKind] = useState("");
  const reports = useQuery({ queryKey: ["reports", kind], queryFn: () => api.reports(kind) });
  const summary = useQuery({ queryKey: ["reports-summary"], queryFn: api.reportsSummary });
  const [toDelete, setToDelete] = useState<Report | null>(null);
  const [deleting, setDeleting] = useState(false);

  const byKind = summary.data?.by_kind ?? {};
  const kinds = Object.keys(byKind);
  const items = reports.data?.reports ?? [];

  const del = async () => {
    if (!toDelete) return; setDeleting(true);
    try { await api.deleteReport(toDelete.id); push("Report deleted", "success"); invalidate("reports", "reports-summary"); }
    catch (e: any) { push(e.message, "error"); } finally { setDeleting(false); setToDelete(null); }
  };

  const isJson = (p: string) => p.toLowerCase().endsWith(".json");

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2">
        <button onClick={() => setKind("")} className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition-all ${kind === "" ? "bg-brand-600 text-white" : "surface-2 text-muted hover:text-[rgb(var(--text))]"}`}>
          All {summary.data ? `(${fmt(Object.values(byKind).reduce((s, n) => s + n, 0))})` : ""}
        </button>
        {kinds.map((k) => (
          <button key={k} onClick={() => setKind(k)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold capitalize transition-all ${kind === k ? "bg-brand-600 text-white" : "surface-2 text-muted hover:text-[rgb(var(--text))]"}`}>
            {k.replace(/_/g, " ")} ({fmt(byKind[k])})
          </button>
        ))}
      </div>

      <Card className="overflow-hidden p-0">
        {reports.isLoading ? (
          <div className="space-y-2 p-4">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-16" />)}</div>
        ) : !items.length ? (
          <EmptyState icon={<FileText className="h-10 w-10" />} title="No reports" hint="Reports generated by panel analysis, inspection and training appear here." />
        ) : (
          <div className="divide-y divide-[rgb(var(--border))]">
            {items.map((r) => (
              <div key={r.id} className="flex items-center gap-3 px-4 py-3.5 hover:bg-[rgb(var(--surface-2))]">
                <div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-brand-500/15 text-brand-400">
                  {isJson(r.path) ? <FileJson className="h-5 w-5" /> : <FileText className="h-5 w-5" />}
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <p className="truncate font-semibold">{r.title}</p>
                    <Badge tone={KIND_TONE[r.kind] || "gray"}>{r.kind}</Badge>
                  </div>
                  <p className="truncate text-xs text-muted">{summaryText(r.summary)} · {timeAgo(r.created_at)}</p>
                </div>
                <a className="btn-outline btn-sm" href={mediaUrl(r.path)} target="_blank" rel="noreferrer"><Download className="h-3.5 w-3.5" /> Open</a>
                <button className="btn-icon btn-ghost text-rose-500" onClick={() => setToDelete(r)}><Trash2 className="h-4 w-4" /></button>
              </div>
            ))}
          </div>
        )}
      </Card>

      <ConfirmDialog open={Boolean(toDelete)} onClose={() => setToDelete(null)} onConfirm={del} loading={deleting}
        title="Delete report" message={<>Delete <b>{toDelete?.title}</b>? This cannot be undone.</>} />
    </div>
  );
}
